// Curriculum words for the Ear Sprint "Where does the pitch drop?" mode. dropAfter
// = mora after which the pitch falls (0 = heiban / no drop). Verified: the app's
// own detector on the Kyoko audio AGREES with the dictionary nucleus, so the
// answer matches both the audio and the canonical accent. Audio: /word-audio/<word>.mp3

export interface DropWord { word: string; reading: string; en: string; morae: string[]; dropAfter: number; }

export const DROP_WORDS: DropWord[] = [
  { word: '水', reading: 'みず', en: 'water 💧', morae: ['み', 'ず'], dropAfter: 0 },
  { word: '日本', reading: 'にほん', en: 'Japan 🇯🇵', morae: ['に', 'ほ', 'ん'], dropAfter: 2 },
  { word: '飴', reading: 'あめ', en: 'candy 🍬', morae: ['あ', 'め'], dropAfter: 0 },
  { word: '卵', reading: 'たまご', en: 'egg 🥚', morae: ['た', 'ま', 'ご'], dropAfter: 2 },
  { word: '鼻', reading: 'はな', en: 'nose 👃', morae: ['は', 'な'], dropAfter: 0 },
  { word: '雨', reading: 'あめ', en: 'rain 🌧', morae: ['あ', 'め'], dropAfter: 1 },
  { word: '口', reading: 'くち', en: 'mouth 👄', morae: ['く', 'ち'], dropAfter: 0 },
  { word: '箸', reading: 'はし', en: 'chopsticks 🥢', morae: ['は', 'し'], dropAfter: 1 },
  { word: '顔', reading: 'かお', en: 'face 😊', morae: ['か', 'お'], dropAfter: 0 },
  { word: '母', reading: 'はは', en: 'mother 👩', morae: ['は', 'は'], dropAfter: 1 },
  { word: '果物', reading: 'くだもの', en: 'fruit 🍎', morae: ['く', 'だ', 'も', 'の'], dropAfter: 2 },
  { word: '猫', reading: 'ねこ', en: 'cat 🐈', morae: ['ね', 'こ'], dropAfter: 1 },
  { word: '海', reading: 'うみ', en: 'sea 🌊', morae: ['う', 'み'], dropAfter: 1 },
  { word: '先生', reading: 'せんせい', en: 'teacher 🧑‍🏫', morae: ['せ', 'ん', 'せ', 'い'], dropAfter: 3 },
  { word: '時間', reading: 'じかん', en: 'time ⏰', morae: ['じ', 'か', 'ん'], dropAfter: 0 },
  { word: '空', reading: 'そら', en: 'sky ☁️', morae: ['そ', 'ら'], dropAfter: 1 },
  { word: '仕事', reading: 'しごと', en: 'work 💼', morae: ['し', 'ご', 'と'], dropAfter: 0 },
  { word: '車', reading: 'くるま', en: 'car 🚗', morae: ['く', 'る', 'ま'], dropAfter: 0 },
  { word: '夜', reading: 'よる', en: 'night 🌙', morae: ['よ', 'る'], dropAfter: 1 },
  { word: '野菜', reading: 'やさい', en: 'vegetable 🥬', morae: ['や', 'さ', 'い'], dropAfter: 0 },
  { word: '駅', reading: 'えき', en: 'station 🚉', morae: ['え', 'き'], dropAfter: 1 },
  { word: '魚', reading: 'さかな', en: 'fish 🐟', morae: ['さ', 'か', 'な'], dropAfter: 0 },
  { word: '本', reading: 'ほん', en: 'book 📖', morae: ['ほ', 'ん'], dropAfter: 1 },
  { word: '時計', reading: 'とけい', en: 'clock 🕐', morae: ['と', 'け', 'い'], dropAfter: 0 },
  { word: '鞄', reading: 'かばん', en: 'bag 👜', morae: ['か', 'ば', 'ん'], dropAfter: 0 },
  { word: '学校', reading: 'がっこう', en: 'school 🏫', morae: ['が', 'っ', 'こ', 'う'], dropAfter: 0 },
  { word: '眼鏡', reading: 'めがね', en: 'glasses 👓', morae: ['め', 'が', 'ね'], dropAfter: 1 },
  { word: '会社', reading: 'かいしゃ', en: 'company 🏢', morae: ['か', 'い', 'しゃ'], dropAfter: 0 },
  { word: '旅行', reading: 'りょこう', en: 'travel ✈️', morae: ['りょ', 'こ', 'う'], dropAfter: 0 },
  { word: '質問', reading: 'しつもん', en: 'question ❓', morae: ['し', 'つ', 'も', 'ん'], dropAfter: 0 },
  { word: '新聞', reading: 'しんぶん', en: 'newspaper 📰', morae: ['し', 'ん', 'ぶ', 'ん'], dropAfter: 0 },
  { word: '電車', reading: 'でんしゃ', en: 'train 🚃', morae: ['で', 'ん', 'しゃ'], dropAfter: 0 },
  { word: '蜜柑', reading: 'みかん', en: 'mandarin 🍊', morae: ['み','か','ん'], dropAfter: 1 },
  { word: '珈琲', reading: 'コーヒー', en: 'coffee ☕', morae: ['コ','ー','ヒ','ー'], dropAfter: 3 },
  { word: '図書館', reading: 'としょかん', en: 'library 📚', morae: ['と','しょ','か','ん'], dropAfter: 2 },
  { word: '窓', reading: 'まど', en: 'window 🪟', morae: ['ま','ど'], dropAfter: 1 },
  { word: '机', reading: 'つくえ', en: 'desk 🗄️', morae: ['つ','く','え'], dropAfter: 0 },
  { word: '手紙', reading: 'てがみ', en: 'letter ✉️', morae: ['て','が','み'], dropAfter: 0 },
  { word: '写真', reading: 'しゃしん', en: 'photo 📷', morae: ['しゃ','し','ん'], dropAfter: 0 },
  { word: '声', reading: 'こえ', en: 'voice 🗣️', morae: ['こ','え'], dropAfter: 1 },
  { word: '自転車', reading: 'じてんしゃ', en: 'bicycle 🚲', morae: ['じ','て','ん','しゃ'], dropAfter: 0 },
  { word: '星', reading: 'ほし', en: 'star ⭐', morae: ['ほ','し'], dropAfter: 0 },
  { word: '雲', reading: 'くも', en: 'cloud ☁️', morae: ['く','も'], dropAfter: 1 },
  { word: '風', reading: 'かぜ', en: 'wind 🌬️', morae: ['か','ぜ'], dropAfter: 0 },
  { word: '庭', reading: 'にわ', en: 'garden 🌳', morae: ['に','わ'], dropAfter: 0 },
  { word: '国', reading: 'くに', en: 'country 🗺️', morae: ['く','に'], dropAfter: 0 },
  { word: '大人', reading: 'おとな', en: 'adult 🧑', morae: ['お','と','な'], dropAfter: 0 },
  { word: '兄', reading: 'あに', en: 'older brother 👦', morae: ['あ','に'], dropAfter: 1 },
  { word: 'パン', reading: 'パン', en: 'bread 🍞', morae: ['パ','ン'], dropAfter: 1 },
  { word: '階段', reading: 'かいだん', en: 'stairs 🪜', morae: ['か','い','だ','ん'], dropAfter: 0 },
  { word: '雑誌', reading: 'ざっし', en: 'magazine 📖', morae: ['ざ','っ','し'], dropAfter: 0 },
  { word: '辞書', reading: 'じしょ', en: 'dictionary 📕', morae: ['じ','しょ'], dropAfter: 1 },
  { word: 'コップ', reading: 'コップ', en: 'cup 🥛', morae: ['コ','ッ','プ'], dropAfter: 0 },
  { word: 'パソコン', reading: 'パソコン', en: 'computer 💻', morae: ['パ','ソ','コ','ン'], dropAfter: 0 },
  { word: '切符', reading: 'きっぷ', en: 'ticket 🎫', morae: ['き','っ','ぷ'], dropAfter: 0 },
  { word: 'お金', reading: 'おかね', en: 'money 💰', morae: ['お','か','ね'], dropAfter: 0 },
  { word: '昨日', reading: 'きのう', en: 'yesterday 📆', morae: ['き','の','う'], dropAfter: 2 },
  { word: '鳥', reading: 'とり', en: 'bird 🐦', morae: ['と','り'], dropAfter: 0 },
  { word: '意味', reading: 'いみ', en: 'meaning 💭', morae: ['い','み'], dropAfter: 1 },
  { word: '野球', reading: 'やきゅう', en: 'baseball ⚾', morae: ['や','きゅ','う'], dropAfter: 0 },
  { word: '切手', reading: 'きって', en: 'stamp 📮', morae: ['き','っ','て'], dropAfter: 0 },
  { word: '散歩', reading: 'さんぽ', en: 'walk 🚶', morae: ['さ','ん','ぽ'], dropAfter: 0 },
  { word: '地図', reading: 'ちず', en: 'map 🗺️', morae: ['ち','ず'], dropAfter: 1 },
  { word: '壁', reading: 'かべ', en: 'wall 🧱', morae: ['か','べ'], dropAfter: 0 },
  { word: '森', reading: 'もり', en: 'forest 🌲', morae: ['も','り'], dropAfter: 0 },
  { word: '地球', reading: 'ちきゅう', en: 'earth 🌏', morae: ['ち','きゅ','う'], dropAfter: 0 },
  { word: '布団', reading: 'ふとん', en: 'futon 🛏️', morae: ['ふ','と','ん'], dropAfter: 0 },
];
