// Curated, pattern-ordered pitch-accent curriculum (heiban → atamadaka →
// nakadaka/odaka). Readings verified against public/pitch-accents.json.
// Audio: public/pitch-audio/<word>.mp3 (generate via scripts/gen-pitch-audio.mjs).

export interface PracticeWord { word: string; reading: string; meaning: string; }

export const PRACTICE_WORDS: PracticeWord[] = [
  { word: '水', reading: 'みず', meaning: 'water' },
  { word: '飴', reading: 'あめ', meaning: 'candy' },
  { word: '鼻', reading: 'はな', meaning: 'nose' },
  { word: '口', reading: 'くち', meaning: 'mouth' },
  { word: '顔', reading: 'かお', meaning: 'face' },
  { word: '電話', reading: 'でんわ', meaning: 'telephone' },
  { word: '名前', reading: 'なまえ', meaning: 'name' },
  { word: '時間', reading: 'じかん', meaning: 'time' },
  { word: '仕事', reading: 'しごと', meaning: 'work; job' },
  { word: '車', reading: 'くるま', meaning: 'car' },
  { word: '野菜', reading: 'やさい', meaning: 'vegetables' },
  { word: '魚', reading: 'さかな', meaning: 'fish' },
  { word: '時計', reading: 'とけい', meaning: 'clock; watch' },
  { word: '財布', reading: 'さいふ', meaning: 'wallet' },
  { word: '鞄', reading: 'かばん', meaning: 'bag' },
  { word: '学生', reading: 'がくせい', meaning: 'student' },
  { word: '友達', reading: 'ともだち', meaning: 'friend' },
  { word: '学校', reading: 'がっこう', meaning: 'school' },
  { word: '会社', reading: 'かいしゃ', meaning: 'company' },
  { word: '旅行', reading: 'りょこう', meaning: 'trip; travel' },
  { word: '質問', reading: 'しつもん', meaning: 'question' },
  { word: '問題', reading: 'もんだい', meaning: 'problem' },
  { word: '新聞', reading: 'しんぶん', meaning: 'newspaper' },
  { word: '電車', reading: 'でんしゃ', meaning: 'train' },
  { word: '勉強', reading: 'べんきょう', meaning: 'study' },
  { word: '牛乳', reading: 'ぎゅうにゅう', meaning: 'milk' },
  { word: '手', reading: 'て', meaning: 'hand' },
  { word: '目', reading: 'め', meaning: 'eye' },
  { word: '雨', reading: 'あめ', meaning: 'rain' },
  { word: '箸', reading: 'はし', meaning: 'chopsticks' },
  { word: '母', reading: 'はは', meaning: 'mother' },
  { word: '猫', reading: 'ねこ', meaning: 'cat' },
  { word: '海', reading: 'うみ', meaning: 'sea' },
  { word: '空', reading: 'そら', meaning: 'sky' },
  { word: '朝', reading: 'あさ', meaning: 'morning' },
  { word: '夜', reading: 'よる', meaning: 'night' },
  { word: '駅', reading: 'えき', meaning: 'station' },
  { word: '本', reading: 'ほん', meaning: 'book' },
  { word: '元気', reading: 'げんき', meaning: 'healthy; energetic' },
  { word: '今日', reading: 'きょう', meaning: 'today' },
  { word: '家族', reading: 'かぞく', meaning: 'family' },
  { word: '映画', reading: 'えいが', meaning: 'movie' },
  { word: '天気', reading: 'てんき', meaning: 'weather' },
  { word: '眼鏡', reading: 'めがね', meaning: 'glasses' },
  { word: '音楽', reading: 'おんがく', meaning: 'music' },
  { word: '料理', reading: 'りょうり', meaning: 'cooking; dish' },
  { word: '山', reading: 'やま', meaning: 'mountain' },
  { word: '川', reading: 'かわ', meaning: 'river' },
  { word: '橋', reading: 'はし', meaning: 'bridge' },
  { word: '花', reading: 'はな', meaning: 'flower' },
  { word: '父', reading: 'ちち', meaning: 'father' },
  { word: '犬', reading: 'いぬ', meaning: 'dog' },
  { word: '店', reading: 'みせ', meaning: 'shop' },
  { word: '足', reading: 'あし', meaning: 'foot; leg' },
  { word: '耳', reading: 'みみ', meaning: 'ear' },
  { word: '肉', reading: 'にく', meaning: 'meat' },
  { word: '塩', reading: 'しお', meaning: 'salt' },
  { word: '日本', reading: 'にほん', meaning: 'Japan' },
  { word: '卵', reading: 'たまご', meaning: 'egg' },
  { word: '砂糖', reading: 'さとう', meaning: 'sugar' },
  { word: '飛行機', reading: 'ひこうき', meaning: 'airplane' },
  { word: '果物', reading: 'くだもの', meaning: 'fruit' },
  { word: '自転車', reading: 'じてんしゃ', meaning: 'bicycle' },
  { word: '明日', reading: 'あした', meaning: 'tomorrow' },
  { word: '頭', reading: 'あたま', meaning: 'head' },
  { word: '先生', reading: 'せんせい', meaning: 'teacher' },
];
